#!/bin/sh

if test -z "$1" -o -z "$2"; then
  echo "usage: $0 alt.img neu.img"
  exit 1
fi

#if test -z "$3"; then
#  RDIR="."
#else
#  RDIR="$3"
#fi 

RDIR="rdiffs"

PREV=$1
NEW=$2


#      echo $PREV $NEW
      PRE=$(echo $PREV|cut -d- -f1-3)
#     POST=$(echo $PREV|cut -d- -f8)
      POST="i386.rdiff"
      FIRST=$(echo $PREV|cut -d- -f4-7)
      SECOND=$(echo $NEW|cut -d- -f4-7)
      RDIFF="${PRE}-${FIRST}--${SECOND}-${POST}"
#     RDIFF=$(get_rdiff_filename $PREV $N)
      echo -n "$RDIFF: "


if ! test -e $PREV.sig; then
    echo -n "signature "
    if ! test -e $PREV; then
	echo "no img"
	exit 1
    else
        rdiff signature $PREV $PREV.sig
    fi
fi
if ! test -e $RDIR/$RDIFF; then
   echo -n "delta "
   rdiff delta $PREV.sig $NEW $RDIR/$RDIFF
fi
echo "ok"

exit $?
