#!/bin/sh   

CURRENT_IMAGE="$(cat /etc/ltsp/this_ltspimage_name).img"
NEW_IMAGE=$(basename $1)


echo "****************************************************************"
echo "*                                                              *"
echo "*                     amxa-laptop-image install                *"
echo "*                                                              *"
echo "****************************************************************"
echo
date
echo

if ! test "$(cat /etc/puavo/hosttype)" = "laptop"; then
  echo "runs only on laptops. exiting ..."
  exit 1
fi

if test -z "$1"; then
  echo "usage: amxa-laptop-install-image path/to/image.img"
  exit 1
fi


if ! test -e $1; then
  echo "image not found. exiting..."
  exit 1
fi

if  test "$CURRENT_IMAGE" = "$NEW_IMAGE"; then
  echo "cannot overwrtite current image. exiting..."
  exit 1
fi

echo
echo $1
echo "cp $1 /images/."
echo
echo "$CURRENT_IMAGE is currrent"
echo "$NEW_IMAGE is new"
echo 


#cd /images/
echo
pwd
echo
#echo "$CURRENT_IMAGE --- $NEW_IMAGE"



####################3löschen
for N in $(ls /images/ltsp*); do
  NN=$(basename $N)
  if ! test  "$NN" = "$CURRENT_IMAGE"; then
      #if ! test "$NN" = "$NEW_IMAGE"; then
         echo "rm $N"
         rm $N
      #fi
  fi
done 


####################instalieren
#echo "$CURRENT_IMAGE --- $NEW_IMAGE"

    echo "cp $1 /images/."
    if ! cp $1 /images/.; then
      echo "could not copy image. exiting..."
      exit 1
    fi



# set hard links ##########3
 CNT=0;
 for N in $(ls -t /images/ltsp-amxa-*-i386*); do
    CNT=$(( $CNT + 1 )) 
    case $CNT in 
      1) ln $N /images/ltsp.img
         echo "ln $N /images/ltsp.img"         
         ;;
      2) ln $N /images/ltsp-backup.img
         echo "ln $N /images/ltsp-backup.img"
         ;;
      *) echo -n ""
         ;;
    esac
  done 



  echo
  echo "fertig"
  echo
  echo

exit 0
