#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

#
# Function that starts the daemon/service
#
do_start()
{
   amxa-laptop-update-image&
   exit 0
}

#
# Function that stops the daemon/service
#
do_stop()
{
  echo ""
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
  do_stop
  do_start
}

case "$1" in
  start)
        do_start
	;;
  stop)
        do_stop
	;;
  restart)
        do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start}" >&2
	echo "Usage: $SCRIPTNAME {start}" >&2
	exit 3
	;;
esac

